### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [ ]:
import numpy as np

vector = np.random.random(10)
matrix = np.arange(11, 36, step = 3).reshape(3, 3)
# або
matrix = np.array([[11,14,17],[20,23,26], [29,32,35]])


display(vector, matrix)
display(vector.shape, matrix.shape)

array([0.20531326, 0.48426067, 0.07511455, 0.67938971, 0.30071151,
       0.82980122, 0.48422857, 0.93616636, 0.58166143, 0.50890838])

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

(10,)

(3, 3)


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [ ]:
vector_plus_10 = np.round(vector + 10, 2)
matrix_mult_2 = matrix * 2

vector_squared = vector ** 2 # те саме що vector*vector - унікальний випадок, де ми використовуємо поелементне множення

display(vector_plus_10, matrix_mult_2, vector_squared)

array([10.75, 10.44, 10.07, 10.15, 10.19, 10.01, 10.68, 10.7 , 10.47,
       10.63])

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

array([5.56598933e-01, 1.97985982e-01, 5.26198324e-03, 2.23114272e-02,
       3.63147192e-02, 1.99166000e-04, 4.65303445e-01, 4.89215378e-01,
       2.20174801e-01, 4.00230837e-01])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [ ]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [ ]:
result_matrix = np.dot(B, A)
display(result_matrix)

result_matrix_dot_C = np.dot(result_matrix, C)
display(result_matrix_dot_C)

result_matrix_dot_D = np.dot(result_matrix, D)
display(result_matrix_dot_D)

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

array([[0.5202],
       [0.2846]])

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [ ]:
matrix_transposed = result_matrix.T
display(matrix_transposed)

vector_transposed = vector.T
display(vector_transposed, vector_transposed.shape)

column_vector = np.expand_dims(vector, axis=1)
column_vector_transposed = column_vector.T
display(column_vector_transposed, column_vector.shape, column_vector_transposed.shape)


array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

array([0.46057818, 0.89022107, 0.21482669, 0.18328639, 0.88493138,
       0.87898642, 0.5773989 , 0.67998153, 0.23606285, 0.84696177])

(10,)

array([[0.46057818, 0.89022107, 0.21482669, 0.18328639, 0.88493138,
        0.87898642, 0.5773989 , 0.67998153, 0.23606285, 0.84696177]])

(10, 1)

(1, 10)