### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [3]:
import random
import numpy as np

In [35]:
v1 = np.array([random.uniform(0, 1) for _ in range(10)])
v2 = np.random.rand(10, 1)
print(v1, "Розмір:", v1.shape)
print(v2, "Розмір:", v2.shape)

[0.46511008 0.45088354 0.80905373 0.62494962 0.3775496  0.33502547
 0.95236961 0.82840072 0.70529371 0.20430997] Розмір: (10,)
[[0.65996348]
 [0.14578793]
 [0.52764737]
 [0.91214747]
 [0.50273029]
 [0.00668027]
 [0.73723078]
 [0.99012129]
 [0.96737638]
 [0.31837798]] Розмір: (10, 1)


In [27]:
A = np.array([[11, 14, 17],
              [20, 23, 26],
              [29, 32, 35]])
A, A.shape

(array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]),
 (3, 3))


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [36]:
v1_add10 = (v1 + 10).round(2)
v2_add10 = (v2 + 10).round(2)
print(v1_add10)
print(v2_add10)

[10.47 10.45 10.81 10.62 10.38 10.34 10.95 10.83 10.71 10.2 ]
[[10.66]
 [10.15]
 [10.53]
 [10.91]
 [10.5 ]
 [10.01]
 [10.74]
 [10.99]
 [10.97]
 [10.32]]


In [38]:
A_mult2 = A * 2
A_mult2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [39]:
v1_squared = v1 ** 2
v2_squared = v2 ** 2
print(v1_squared)
print(v2_squared)

[0.21632739 0.20329597 0.65456793 0.39056203 0.1425437  0.11224206
 0.90700787 0.68624776 0.49743922 0.04174256]
[[4.35551797e-01]
 [2.12541211e-02]
 [2.78411752e-01]
 [8.32013005e-01]
 [2.52737745e-01]
 [4.46259792e-05]
 [5.43509217e-01]
 [9.80340178e-01]
 [9.35817052e-01]
 [1.01364538e-01]]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [40]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [43]:
result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [45]:
matrix_C = np.dot(result_matrix, C)
matrix_C, matrix_C.shape

(array([[0.5202],
        [0.2846]]),
 (2, 1))

In [46]:
matrix_D = np.dot(result_matrix, D)
matrix_D, matrix_D.shape

(array([[0.5202, 0.7281],
        [0.2846, 0.2034]]),
 (2, 2))

множення будь-якої матриці на одиничну не змінює цю матрицю.


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [47]:
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [50]:
v1.T, v1.T.shape

(array([0.46511008, 0.45088354, 0.80905373, 0.62494962, 0.3775496 ,
        0.33502547, 0.95236961, 0.82840072, 0.70529371, 0.20430997]),
 (10,))

In [54]:
v2_T = v2.T
v2_T, v2_T.shape

(array([[0.65996348, 0.14578793, 0.52764737, 0.91214747, 0.50273029,
         0.00668027, 0.73723078, 0.99012129, 0.96737638, 0.31837798]]),
 (1, 10))

По вектору v1 транспонування не спрацювало мабудь тому, що вектор-рядок був одновимірним і Python не зміг його перевернути.  
Що до вектору v2 то Python транспонував його у рядок.

In [55]:
column_vector = np.expand_dims(v1, axis=1)
print("Оригінальний вектор:\n", v1, v1.shape)
print("\nНовий column_vector:\n", column_vector, column_vector.shape)

Оригінальний вектор:
 [0.46511008 0.45088354 0.80905373 0.62494962 0.3775496  0.33502547
 0.95236961 0.82840072 0.70529371 0.20430997] (10,)

Новий column_vector:
 [[0.46511008]
 [0.45088354]
 [0.80905373]
 [0.62494962]
 [0.3775496 ]
 [0.33502547]
 [0.95236961]
 [0.82840072]
 [0.70529371]
 [0.20430997]] (10, 1)


column_vector став двовимірним вектором-стовпцем

In [56]:
column_vector.T, column_vector.T.shape

(array([[0.46511008, 0.45088354, 0.80905373, 0.62494962, 0.3775496 ,
         0.33502547, 0.95236961, 0.82840072, 0.70529371, 0.20430997]]),
 (1, 10))